In [28]:
import tensorflow as tf
import numpy as np

print(f"TensorFlow version: {tf.__version__}")

TensorFlow version: 2.6.0


# Load Dataset
Load and prepare MNIST dataset

In [29]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [37]:
# 3-Layer NN, returns logits/log-odds scores for each class
# using softmax activation fn is more interpretable but
# it makes it impossible to provide exact loss calculations
# when taking direct softmax output
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
    # tf.keras.layers.Dense(10, activation='softmax')

])

predictions = model(x_train[:1]).numpy()
tf.nn.softmax(predictions).numpy()

array([[0.06744027, 0.0536022 , 0.05078283, 0.11670015, 0.13474101,
        0.07511835, 0.08161858, 0.15270185, 0.06095554, 0.20633927]],
      dtype=float32)

In [44]:
# Define a loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=1)
expected_loss = -tf.math.log(0.1).numpy() # untrained model returns ~0.1 for each class
actual_loss = loss_fn(y_train[:1], predictions).numpy()

# Define optimization fn, loss fn and metric
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

# Fit the model on the training data
model.fit(x_train, y_train, epochs=5)

2021-12-27 11:43:55.857076: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:185] None of the MLIR Optimization Passes are enabled (registered 2)


Epoch 1/5
1875/1875 [==============================] - 2s 941us/step - loss: 0.2967 - accuracy: 0.9126
Epoch 2/5
1875/1875 [==============================] - 2s 925us/step - loss: 0.1430 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 2s 950us/step - loss: 0.1097 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 2s 887us/step - loss: 0.0893 - accuracy: 0.9728
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0757 - accuracy: 0.9764


In [50]:
# Evaluate the loss and metric you preset
model.evaluate(x_test, y_test)

# Give softmax activation layer to output probs.
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

# Get prob. predictions
probability_model(x_test[:1])

313/313 [==============================] - 0s 731us/step - loss: 0.0731 - accuracy: 0.9772


<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[1.7080716e-08, 2.1538952e-07, 8.8657152e-06, 2.4071573e-04,
        3.7906167e-10, 6.7671991e-08, 1.8379211e-13, 9.9974734e-01,
        9.6266078e-08, 2.6042221e-06]], dtype=float32)>