In [1]:
import tensorflow as tf
import numpy as np

print(f"TensorFlow version: {tf.__version__}")

TensorFlow version: 2.7.0


# Load Dataset
Load and prepare MNIST dataset

In [2]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [13]:
# 3-Layer NN, returns logits/log-odds scores for each class
# using softmax activation fn is more interpretable but
# it makes it impossible to provide exact loss calculations
# when taking direct softmax output
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
    # tf.keras.layers.Dense(10, activation='softmax')

])

predictions = model(x_train[:1]).numpy()
tf.nn.softmax(predictions).numpy()

array([[0.05380765, 0.09167878, 0.16701175, 0.06801457, 0.1538028 ,
        0.11396313, 0.07750425, 0.0696799 , 0.16497341, 0.03956374]],
      dtype=float32)

In [4]:
# Define a loss function
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=1)
expected_loss = -tf.math.log(0.1).numpy() # untrained model returns ~0.1 for each class
actual_loss = loss_fn(y_train[:1], predictions).numpy()

# Define optimization fn, loss fn and metric
model.compile(
    optimizer='adam',
    loss=loss_fn,
    metrics=['accuracy']
)

# Fit the model on the training data
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 3s 1ms/step - loss: 0.2913 - accuracy: 0.9147
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1403 - accuracy: 0.9589
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1066 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0857 - accuracy: 0.9735
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.0733 - accuracy: 0.9770


In [5]:
# Evaluate the loss and metric you preset
model.evaluate(x_test, y_test)

# Give softmax activation layer to output probs.
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

# Get prob. predictions
probability_model(x_test[:1])

313/313 [==============================] - 0s 944us/step - loss: 0.0750 - accuracy: 0.9769


<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[4.13414654e-08, 1.43459919e-08, 1.11738314e-06, 4.43729114e-05,
        2.74582093e-12, 1.40822065e-08, 4.68365784e-14, 9.99954343e-01,
        1.03048403e-09, 8.02697215e-08]], dtype=float32)>